### ISSUE TITLE
Doesn't walk incomplete declaration

### ISSUE THREAD

**Issue by knownasilya** [postcss/postcss-safe-parser#9]
```css
.container {
  max-width: rem(800px);
  margin: 3rem auto 5rem;
  padding: 0 2rem;
  font-size

  @media (max-width: rem(800px)) {
    flex-direction: column;
    margin-top: 0.5rem;
  }
}
```

It ignores `font-size` (with or without :, no difference). Mainly I'm using this for autocomplete.
My code is here: https://github.com/subsetcss/parser/blob/master/src/index.ts#L42

walked declarations go from `padding` to `flex-direction`.
